[package]
name = "brixo-client"
version = "0.1.0"
edition = "2024"

[dependencies]
brixo-core = { path = "../brixo-core" }
brixo-render = { path = "../brixo-render" }
brixo-runtime = { path = "../brixo-runtime" }
glam = "0.33"
egui = "0.31"
brixo-audio = { path = "../brixo-audio" }
winit = "0.30"
ureq = { version = "2", features = ["json"] }
serde_json = "1"
