[package]
name = "brixo-studio"
version = "0.1.0"
edition = "2024"

[dependencies]
brixo-core = { path = "../brixo-core" }
brixo-render = { path = "../brixo-render" }
bytemuck = { version = "1", features = ["derive"] }
egui = "0.31"
egui-wgpu = "0.31"
egui-winit = "0.31"
glam = "0.33"
pollster = "0.4"
wgpu = "24"
winit = "0.30"
brixo-runtime = { path = "../brixo-runtime" }
rovik = { path = "../rovik" }
brixo-client = { path = "../brixo-client" }
brixo-server = { path = "../brixo-server" }
