[package]
name = "brixo-player"
version = "0.1.0"
edition = "2024"

[dependencies]
brixo-client = { path = "../brixo-client" }
brixo-core = { path = "../brixo-core" }
brixo-render = { path = "../brixo-render" }
brixo-runtime = { path = "../brixo-runtime" }
egui = "0.31"
egui-wgpu = "0.31"
egui-winit = "0.31"
glam = "0.33"
pollster = "0.4"
wgpu = "24"
winit = "0.30"
brixo-server = { path = "../brixo-server" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[build-dependencies]
winresource = "0.1"
cc = "1"
